version: '3'

services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - project

  edgedb:
    image: edgedb/edgedb
    env_file:
      - .env
    volumes:
      - .dbdata:/var/lib/edgedb/data # Data persistence
      - "./dbschema:/dbschema"      # Schema persistence    
    ports:
      - "5656:5656"
    networks:
      - project


networks: 
  project:

volumes:
  dbdata: